"use client";

import styles from "./layout.module.css";
import type { Metadata } from "next";
import Header from "./components/header/header";
import Sidemenu from "./components/sidemenu/sidemenu";
import { usePathname } from "next/navigation";
import ScrollToTopArrow from "./components/scrollToTopArrow/ScrollToTopArrow";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const pathName = usePathname();

  return (
    <html lang="en" style={{ fontFamily: "SoraRegular" }}>
      <body>
        <div className={styles.layout}>
          <Sidemenu />
          <Header />
          {pathName === "/" && (
            <video autoPlay loop muted className={styles.video}>
              <source src="/backgroundVideo.mp4" type="video/mp4" />
            </video>
          )}
        </div>
        {children}
      </body>
    </html>
  );
}
