import styles from "./page.module.css";
import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import Header from "./components/header/header";
import Sidemenu from "./components/sidemenu/sidemenu";

const sans = Open_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={sans.className}>
      <body>
        <div className={styles.layout}>
          <Sidemenu />
          <Header />
        </div>       
        <div className={styles.children}>
          <main>{children}</main>
        </div>
          
      </body>
    </html>
  );
}
